version: '3.7'
services:
  dummy:
    build:
      context: ./
      dockerfile: docker/ubuntu/Dockerfile
      labels:
        io.simcore.name: '{"name": "dummy"}'
        io.simcore.thumbnail: '{"thumbnail": "https://github.com/ITISFoundation/osparc-assets/blob/cb43207b6be2f4311c93cd963538d5718b41a023/assets/default-thumbnail-cookiecutter-osparc-service.png?raw=true"}'
        io.simcore.description: '{"description": "dummy"}'
        io.simcore.key: '{"key": "simcore/services/comp/dummy"}'
        io.simcore.version: '{"version": "0.1.0"}'
        io.simcore.integration-version: '{"integration-version": "2.0.0"}'
        io.simcore.type: '{"type": "computational"}'
        io.simcore.authors: '{"authors": [{"name": "asdf", "email": "asdf@email.com",
          "affiliation": "sdfas"}]}'
        io.simcore.contact: '{"contact": "asdf@email.com"}'
        io.simcore.inputs: '{"inputs": {"input_1": {"displayOrder": 1.0, "label":
          "input_1_label", "description": "The input 1 description", "type": "string",
          "fileToKeyMap": {"somefilename.ext": "input_1"}, "defaultValue": "some_value(optional)"}}}'
        io.simcore.outputs: '{"outputs": {"output_1": {"displayOrder": 1.0, "label":
          "output_1_label", "description": "The input 1 description", "type": "string",
          "fileToKeyMap": {"somefilename.ext": "output_1"}}}}'
        org.label-schema.build-date: '2024-08-28T16:31:41Z'
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ''
        org.label-schema.vcs-url: ''
        simcore.service.restart-policy: no-restart
        simcore.service.settings: '[{"name": "Resources", "type": "Resources", "value":
          {"Limits": {"NanoCPUs": 1000000000, "MemoryBytes": 2147483648}}}]'
      target: production
    image: simcore/services/comp/dummy:0.1.0
